# ntSynt CI

jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: |
      mkdir -p ~/miniforge3
      # May 2026 - CI slowed down significantly with mamba 2.6.0+, so using older release for now
      curl -L https://github.com/conda-forge/miniforge/releases/download/26.1.0-0/Miniforge3-Linux-x86_64.sh  -o ~/miniforge3/miniforge.sh
      bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
      rm -rf  ~/miniforge3/miniforge.sh
      ~/miniforge3/bin/conda init bash
      ~/miniforge3/bin/conda init zsh
      export CONDA=$(realpath ~/miniforge3/bin)
      echo "##vso[task.prependpath]$CONDA"
    displayName: Install conda

  - script: conda create --yes --quiet --name ntsynt_viz_ci
    displayName: Create Anaconda environment

  - script: |
      source activate ntsynt_viz_ci
      mamba install --yes -c conda-forge -c bioconda quicktree r-base bioconductor-treeio r-ggpubr bioconductor-ggtree r-phytools r-dplyr r-argparse r-scales r-stringr pylint intervaltree snakemake r-ggplot2 r-gggenomes r-svglite
    displayName: Install dependencies

  - script: |
      source activate ntsynt_viz_ci
      cd bin
      pylint *py
    displayName: Run pylint

  - script: |
      source activate ntsynt_viz_ci
      ./bin/ntsynt_viz.py --help
    displayName: Print ntSynt-viz help message

  - script: |
      source activate ntsynt_viz_ci
      export PATH=$(pwd)/bin:$PATH
      cd tests
      ntsynt_viz.py --blocks great-apes.ntSynt.synteny_blocks.tsv --fais fais.tsv --tree great-apes.mt-tree.nwk --name_conversion great-apes.name-conversions.tsv --normalize --prefix great-apes_ribbon-plots --ribbon_adjust 0.14 --scale 1e9
    displayName: Run Example 1 test (PNG output)

  - script: |
      source activate ntsynt_viz_ci
      export PATH=$(pwd)/bin:$PATH
      cd tests
      ntsynt_viz.py --blocks great-apes.ntSynt.synteny_blocks.tsv --fais fais.tsv  --name_conversion great-apes.name-conversions.tsv  --prefix great-apes_ribbon-plots_no-tree --ribbon_adjust 0.15 --scale 1e9 --target-genome Homo_sapiens --format pdf --force
      diff -q great-apes_ribbon-plots_no-tree_est-distances.order.tsv expected/great-apes_ribbon-plots_no-tree_est-distances.order.tsv
    displayName: Run Example 2 test (PDF output)

  - script: |
      source activate ntsynt_viz_ci
      export PATH=$(pwd)/bin:$PATH
      cd tests
      ntsynt_viz.py --blocks great-apes.ntSynt.synteny_blocks.tsv --fais fais.tsv  --name_conversion great-apes.name-conversions.tsv  --prefix great-apes_ribbon-plots_no-tree \
      --ribbon_adjust 0.15 --scale 2e9 --target-genome Pan_paniscus --format svg --annotate-genomes --force
    displayName: Run Example 3 test (SVG output)

  - script: |
      source activate ntsynt_viz_ci
      export PATH=$(pwd)/bin:$PATH
      cd tests
      ntsynt_viz.py --blocks great-apes.ntSynt.synteny_blocks.tsv --fais fais.tsv  --name_conversion great-apes.name-conversions.tsv  --prefix great-apes_ribbon-plots_tree_order --ribbon_adjust 0.15 --scale 2e9 --order test_order.tsv --format png --force
    displayName: Run Example 4 test (PNG output) 

  - publish: tests/great-apes_ribbon-plots_ribbon-plot_tree.png
    artifact: Example1

  - publish: tests/great-apes_ribbon-plots_no-tree_ribbon-plot.pdf
    artifact: Example2

  - publish: tests/great-apes_ribbon-plots_no-tree_ribbon-plot.svg
    artifact: Example3

  - publish: tests/great-apes_ribbon-plots_tree_order_ribbon-plot.png
    artifact: Example4


- job:
  displayName: macOS-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: |
      mkdir -p ~/miniforge3
      # May 2026 - CI slowed down significantly with mamba 2.6.0+, so using older release for now
      curl -L https://github.com/conda-forge/miniforge/releases/download/26.1.0-0/Miniforge3-MacOSX-x86_64.sh  -o ~/miniforge3/miniforge.sh
      bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
      rm -rf  ~/miniforge3/miniforge.sh
      ~/miniforge3/bin/conda init bash
      ~/miniforge3/bin/conda init zsh
      export CONDA=$(realpath ~/miniforge3/bin)
      echo "##vso[task.prependpath]$CONDA"
    displayName: Install conda

  - script: conda create --yes --quiet --name ntsynt_viz_ci
    displayName: Create Anaconda environment

  - script: |
      source activate ntsynt_viz_ci
      mamba install --yes -c conda-forge -c bioconda quicktree r-base bioconductor-treeio r-ggpubr bioconductor-ggtree r-phytools r-dplyr r-argparse r-scales r-stringr pylint intervaltree snakemake r-ggplot2 r-gggenomes r-svglite
    displayName: Install dependencies

  - script: |
      source activate ntsynt_viz_ci
      cd bin
      pylint *py
    displayName: Run pylint

  - script: |
      source activate ntsynt_viz_ci
      ./bin/ntsynt_viz.py --help
    displayName: Print ntSynt-viz help message

  - script: |
      source activate ntsynt_viz_ci
      export PATH=$(pwd)/bin:$PATH
      cd tests
      ntsynt_viz.py --blocks great-apes.ntSynt.synteny_blocks.tsv --fais fais.tsv --tree great-apes.mt-tree.nwk --name_conversion great-apes.name-conversions.tsv --normalize --prefix great-apes_ribbon-plots --ribbon_adjust 0.14 --scale 1e9 --format png
    displayName: Run Example 1 test (PNG output)

  - script: |
      source activate ntsynt_viz_ci
      export PATH=$(pwd)/bin:$PATH
      cd tests
      ntsynt_viz.py --blocks great-apes.ntSynt.synteny_blocks.tsv --fais fais.tsv  --name_conversion great-apes.name-conversions.tsv  --prefix great-apes_ribbon-plots_no-tree --ribbon_adjust 0.15 --scale 1e9 --target-genome Homo_sapiens --force --format pdf
      diff -q great-apes_ribbon-plots_no-tree_est-distances.order.tsv expected/great-apes_ribbon-plots_no-tree_est-distances.order.tsv
    displayName: Run Example 2 test (PDF output)

  - script: |
      source activate ntsynt_viz_ci
      export PATH=$(pwd)/bin:$PATH
      cd tests
      ntsynt_viz.py --blocks great-apes.ntSynt.synteny_blocks.tsv --fais fais.tsv  --name_conversion great-apes.name-conversions.tsv  --prefix great-apes_ribbon-plots_no-tree --ribbon_adjust 0.15 --scale 2e9 --target-genome Pan_paniscus --format svg --force
    displayName: Run Example 3 test (SVG output)
